DEFAULTS = {
    "label": "\u003cspan\u003e\ue71a\u003c/span\u003e {count}",
    "label_alt": "{next_time} ({countdown})",
    "tooltip": True,
    "update_interval": 600000,  # 10 minutes in milliseconds
    "animation": {"enabled": True, "type": "fadeInOut", "duration": 200},
    "container_padding": {"top": 0, "left": 0, "bottom": 0, "right": 0},
    "callbacks": {"on_left": "toggle_label", "on_middle": "do_nothing", "on_right": "do_nothing"},
    "env_var": "YASB_ICAL_URL",
    "meeting_filter": "all",
    "next_time_format": "%Y-%m-%d %H:%M",
    "horizon_hours": None,
    "timezone_name": None,
    "menu": {
        "blur": True,
        "round_corners": True,
        "round_corners_type": "normal",
        "border_color": "System",
        "alignment": "right",
        "direction": "down",
        "offset_top": 6,
        "offset_left": 0,
    },
    "icons": {
        "online": "\uea64",
        "time": "\uf017",
    },
    "notifications": {
        "enabled": True,
        "offsets_minutes": [10, 0],
        "title": "Upcoming: {summary}",
        "message": "Starts at {start_time} ({countdown})",
        "title_now": "Starting now: {summary}",
        "message_now": "Join now ({start_time})",
        "filter": "all",  # all | online | in_person
        "join_button_text": "Join",
    },
}

VALIDATION_SCHEMA = {
    "label": {"type": "string", "default": DEFAULTS["label"]},
    "label_alt": {"type": "string", "default": DEFAULTS["label_alt"]},
    "tooltip": {"type": "boolean", "required": False, "default": DEFAULTS["tooltip"]},
    "update_interval": {"type": "integer", "default": DEFAULTS["update_interval"], "min": 0, "max": 3600000},
    "animation": {
        "type": "dict",
        "required": False,
        "schema": {
            "enabled": {"type": "boolean", "default": DEFAULTS["animation"]["enabled"]},
            "type": {"type": "string", "default": DEFAULTS["animation"]["type"]},
            "duration": {"type": "integer", "default": DEFAULTS["animation"]["duration"]},
        },
        "default": DEFAULTS["animation"],
    },
    "container_padding": {
        "type": "dict",
        "required": False,
        "schema": {
            "top": {"type": "integer", "default": DEFAULTS["container_padding"]["top"]},
            "left": {"type": "integer", "default": DEFAULTS["container_padding"]["left"]},
            "bottom": {"type": "integer", "default": DEFAULTS["container_padding"]["bottom"]},
            "right": {"type": "integer", "default": DEFAULTS["container_padding"]["right"]},
        },
        "default": DEFAULTS["container_padding"],
    },
    "label_shadow": {
        "type": "dict",
        "required": False,
        "schema": {
            "enabled": {"type": "boolean", "default": False},
            "color": {"type": "string", "default": "black"},
            "offset": {"type": "list", "default": [1, 1]},
            "radius": {"type": "integer", "default": 3},
        },
        "default": {"enabled": False, "color": "black", "offset": [1, 1], "radius": 3},
    },
    "container_shadow": {
        "type": "dict",
        "required": False,
        "schema": {
            "enabled": {"type": "boolean", "default": False},
            "color": {"type": "string", "default": "black"},
            "offset": {"type": "list", "default": [1, 1]},
            "radius": {"type": "integer", "default": 3},
        },
        "default": {"enabled": False, "color": "black", "offset": [1, 1], "radius": 3},
    },
    "env_var": {"type": "string", "required": False, "default": DEFAULTS["env_var"]},
    "meeting_filter": {"type": "string", "allowed": ["all", "online", "in_person"], "default": DEFAULTS["meeting_filter"]},
    "next_time_format": {"type": "string", "default": DEFAULTS["next_time_format"]},
    "horizon_hours": {"nullable": True, "required": False, "type": "integer", "min": 0, "default": DEFAULTS["horizon_hours"]},
    "timezone_name": {"nullable": True, "required": False, "type": "string", "default": DEFAULTS["timezone_name"]},
    "menu": {
        "type": "dict",
        "required": False,
        "schema": {
            "blur": {"type": "boolean", "default": DEFAULTS["menu"]["blur"]},
            "round_corners": {"type": "boolean", "default": DEFAULTS["menu"]["round_corners"]},
            "round_corners_type": {"type": "string", "default": DEFAULTS["menu"]["round_corners_type"]},
            "border_color": {"type": "string", "default": DEFAULTS["menu"]["border_color"]},
            "alignment": {"type": "string", "default": DEFAULTS["menu"]["alignment"]},
            "direction": {"type": "string", "default": DEFAULTS["menu"]["direction"]},
            "offset_top": {"type": "integer", "default": DEFAULTS["menu"]["offset_top"]},
            "offset_left": {"type": "integer", "default": DEFAULTS["menu"]["offset_left"]},
        },
        "default": DEFAULTS["menu"],
    },
    "icons": {
        "type": "dict",
        "required": False,
        "schema": {
            "online": {"type": "string", "default": DEFAULTS["icons"]["online"]},
            "time": {"type": "string", "default": DEFAULTS["icons"]["time"]},
        },
        "default": DEFAULTS["icons"],
    },
    "notifications": {
        "type": "dict",
        "required": False,
        "schema": {
            "enabled": {"type": "boolean", "default": DEFAULTS["notifications"]["enabled"]},
            "offsets_minutes": {"type": "list", "schema": {"type": "integer", "min": 0}, "default": DEFAULTS["notifications"]["offsets_minutes"]},
            "title": {"type": "string", "default": DEFAULTS["notifications"]["title"]},
            "message": {"type": "string", "default": DEFAULTS["notifications"]["message"]},
            "title_now": {"type": "string", "default": DEFAULTS["notifications"]["title_now"]},
            "message_now": {"type": "string", "default": DEFAULTS["notifications"]["message_now"]},
            "filter": {"type": "string", "allowed": ["all", "online", "in_person"], "default": DEFAULTS["notifications"]["filter"]},
            "join_button_text": {"type": "string", "default": DEFAULTS["notifications"]["join_button_text"]},
        },
        "default": DEFAULTS["notifications"],
    },
    "callbacks": {
        "type": "dict",
        "schema": {
            "on_left": {"type": "string", "default": DEFAULTS["callbacks"]["on_left"]},
            "on_middle": {"type": "string", "default": DEFAULTS["callbacks"]["on_middle"]},
            "on_right": {"type": "string", "default": DEFAULTS["callbacks"]["on_right"]},
        },
        "default": DEFAULTS["callbacks"],
    },
}

